### model
model_name_or_path: "/Users/mac/Documents/models/Qwen3-0.6B"
trust_remote_code: true
teacher_model: "/Users/mac/Documents/models/Qwen3-1.7B"
# gradient_checkpointing: false

### method
stage: gkd
do_train: true
finetuning_type: lora
lora_rank: 2
lora_target: "q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj"

### dataset
dataset: openo1_sft
template: qwen3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 2
dataloader_num_workers: 0

### output
output_dir: saves\\Qwen3-0.6B-Instruct\\lora\\train_2025-05-25-14-50-54
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000
resume_from_checkpoint: null
bf16: true

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
